### ISSUE TITLE
Email Verification System While Login 

### ISSUE THREAD

**Issue by pratt0007** [pratt0007/Drive_BOX#3]
An email verification should take place at the time of registration. We can achieve this using python and appending the settings.py file in the project.

**Comment by ShreyaBose04** [comment]
I would like to work on this issue, could you please assign it to me

**Comment by pratt0007** [comment]
Sure!!

**Comment by ShreyaBose04** [comment]
I have added email verification using a link which is currently being sent from my personal email id, which email id should I use in the final code?

**Comment by pratt0007** [comment]
Use this domain to send verification emails.
Gmail: dbox0552@gmail.com
Password: Drive_box2024

**Comment by ShreyaBose04** [comment]
![5a3c04ec-8b66-495d-8003-114449df1da1](https://github.com/pratt0007/Drive_BOX/assets/137882273/3babf2dd-d4ba-44ca-b72d-427edc725c5e)
2 factor authentication needs to be enabled for this account to use less secure apps

**Comment by pratt0007** [comment]
Its enabled!!

**Comment by ShreyaBose04** [comment]
Thanks! I have made the pull request
